name: grocerly_flutter
description: Grocerly — smart, shared grocery lists (Flutter)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  supabase_flutter: ^2.6.0
  uuid: ^4.4.0
  equatable: ^2.0.5
  intl: ^0.19.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  grocerly_data:
    path: ../../packages/data
  grocerly_domain:
    path: ../../packages/domain
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
